ci: Don't write to disk during benchmark runs (#2738)

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -216,11 +216,11 @@ jobs:
           truncate -s "$BIGSIZE" "$TMP/$BIGSIZE"
           # Define the commands to run for each client and server.
           declare -A client_cmd=(
-            ["neqo"]="binaries/neqo/neqo-client _cc _pacing --output-dir . _flags -Q 1 https://$HOST:$PORT/$SIZE"
+            ["neqo"]="binaries/neqo/neqo-client _cc _pacing _disk _flags -Q 1 https://$HOST:$PORT/$SIZE"
             ["msquic"]="msquic/build/bin/Release/quicinterop -test:D -custom:$HOST -port:$PORT -urls:https://$HOST:$PORT/$SIZE"
-            ["google"]="google-quiche/bazel-bin/quiche/quic_client --disable_certificate_verification https://$HOST:$PORT/$SIZE > $SIZE"
-            ["quiche"]="quiche/target/release/quiche-client --dump-responses . --no-verify https://$HOST:$PORT/$SIZE"
-            ["s2n"]="s2n-quic/target/release/s2n-quic-qns interop client --tls rustls --disable-cert-verification --download-dir . --local-ip $HOST https://$HOST:$PORT/$SIZE"
+            ["google"]="google-quiche/bazel-bin/quiche/quic_client --disable_certificate_verification https://$HOST:$PORT/$SIZE"
+            ["quiche"]="quiche/target/release/quiche-client _disk --no-verify https://$HOST:$PORT/$SIZE"
+            ["s2n"]="s2n-quic/target/release/s2n-quic-qns interop client --tls rustls --disable-cert-verification _disk --local-ip $HOST https://$HOST:$PORT/$SIZE"
           )
           declare -A server_cmd=(
             ["neqo"]="binaries/neqo/neqo-server _cc _pacing _flags -Q 1 $HOST:$PORT"
@@ -228,6 +228,14 @@ jobs:
             ["google"]="google-quiche/bazel-bin/quiche/quic_server --generate_dynamic_responses --port $PORT --certificate_file $TMP/cert --key_file $TMP/key"
             ["quiche"]="quiche/target/release/quiche-server --root $TMP --listen $HOST:$PORT --cert $TMP/cert --key $TMP/key"
             ["s2n"]="s2n-quic/target/release/s2n-quic-qns interop server --www-dir $TMP --certificate $TMP/cert --private-key $TMP/key --ip $HOST --port $PORT"
+          )
+          # Flags to append to client_cmd to make the client dump the retrieved file to disk.
+          declare -A disk_flags=(
+            ["neqo"]="--output-dir ."
+            ["msquic"]="" # msquic always dumps to disk :-(
+            ["google"]="" # needs special handling below
+            ["quiche"]="--dump-responses ."
+            ["s2n"]="--download-dir ."
           )
           # Flags to pass to neqo when it runs against another implementation.
           declare -A neqo_flags=(
@@ -245,6 +253,7 @@ jobs:
             local cc=$2
             local pacing=$3
             local flags=$4
+            local disk=$5
             if [[ "$cc" != "" ]]; then
               CMD=${CMD//_cc/--cc $cc}
               EXT="-$cc"
@@ -258,6 +267,7 @@ jobs:
               EXT="$EXT-nopacing"
             fi
             CMD=${CMD//_flags/$flags}
+            CMD=${CMD//_disk/$disk}
           }
 
           # A Welch's t-test to determine if a performance change is statistically significant.
@@ -282,6 +292,7 @@ jobs:
                 echo "Skipping $client vs. $server"
                 continue
               fi
+              echo "*** Running $client vs. $server"
               cp "$(echo "${client_cmd[$client]}" | cut -f1 -d' ')" binaries/
               # google-quiche binaries don't have write permissions by default?!
               chmod u+w binaries/*
@@ -299,21 +310,45 @@ jobs:
               fi
               for cc in "${cc_opt[@]}"; do
                 for pacing in "${pacing_opt[@]}"; do
-                  transmogrify "${server_cmd[$server]}" "$cc" "$pacing" "${neqo_flags[$client]}"
+                  echo "*** Running size verification test for $client vs. $server"
+                  transmogrify "${server_cmd[$server]}" "$cc" "$pacing" "${neqo_flags[$client]}" ""
                   FILENAME="$client-$server$EXT"
                   SERVER_CMD="$CMD"
-                  echo "Server command: $SERVER_CMD"
                   # pkill only matches on the first 15 characters of the command?!
                   SERVER_TAG="$(basename "$(echo "${server_cmd[$server]}" | cut -f1 -d' ')" | cut -c1-15)"
-                  transmogrify "${client_cmd[$client]}" "$cc" "$pacing" "${neqo_flags[$server]}"
-                  echo "Client command: $CMD"
+                  transmogrify "${client_cmd[$client]}" "$cc" "$pacing" "${neqo_flags[$server]}" "${disk_flags[$client]}"
                   cd "$TMP/out"
+
+                  # Do a single test run where we check the size of the file that is downloaded.
+                  # This is to ensure that the server actually served the file, and that the client
+                  # downloaded it. We're not doing this during hyperfine or perf runs, because the
+                  # writing-to-disk incurrs overheads we're not interested in.
+                  # shellcheck disable=SC2086
+                  $WORKSPACE/$SERVER_CMD &
+                  sleep 0.2
+                  if [ "$client" == "google" ]; then
+                    # shellcheck disable=SC2086
+                    $WORKSPACE/$CMD > "$SIZE" 2>&1
+                  else
+                    # shellcheck disable=SC2086
+                    $WORKSPACE/$CMD > /dev/null 2>&1
+                  fi
+                  pkill "$SERVER_TAG"
+                  pgrep "$SERVER_TAG" || true
+                  # Sanity check the size of the last retrieved file.
+                  # google/quiche outputs the HTTP header, too, so we can't just check for -eq.
+                  FILE_SIZE=$(wc -c <"$TMP/out/$SIZE")
+                  if [ "$FILE_SIZE" -lt "$SIZE" ]; then
+                    echo "Error: File size mismatch for $client vs. $server, $SIZE expected, got $FILE_SIZE"
+                    exit 1
+                  fi
+                  # Don't write to disk following this.
+                  transmogrify "${client_cmd[$client]}" "$cc" "$pacing" "${neqo_flags[$server]}" ""
+
                   # Make a tag string for this test.
                   COMMAND="$client vs. $server${cc:+ (}$cc${pacing:+, paced}${cc:+)}"
                   if [[ "$client" == "neqo" || "$server" == "neqo" ]]; then
-                    echo "Generate main-branch results for comparison."
-                    echo "Server command: ${SERVER_CMD/neqo/neqo-main}"
-                    echo "Client command: ${CMD/neqo/neqo-main}"
+                    echo "*** Running main-branch hyperfine tests for $client vs. $server"
                     nice -n -20 setarch --addr-no-randomize hyperfine \
                       --command-name "$COMMAND" --time-unit millisecond  \
                       --export-json "$WORKSPACE/hyperfine-main/$FILENAME.json" \
@@ -323,6 +358,8 @@ jobs:
                       "echo \$\$ >> /cpusets/cpu3/tasks; $WORKSPACE/${CMD/neqo/neqo-main}"
                   fi
 
+                  # Now do the actual hyperfine runs.
+                  echo "*** Running PR-branch hyperfine tests for $client vs. $server"
                   nice -n -20 setarch --addr-no-randomize hyperfine \
                     --command-name "$COMMAND" --time-unit millisecond  \
                     --export-json "$WORKSPACE/hyperfine/$FILENAME.json" \
@@ -332,13 +369,11 @@ jobs:
                     --conclude "pkill $SERVER_TAG" \
                     "echo \$\$ >> /cpusets/cpu3/tasks; $WORKSPACE/$CMD"
 
-                  # Sanity check the size of the last retrieved file.
-                  # google/quiche outputs the HTTP header, too, so we can't just check for -eq.
-                  [ "$(wc -c <"$TMP/out/$SIZE")" -ge "$SIZE" ] || exit 1
-
                   # Do a longer run with perf separately. We used to just wrap the hyperfine command above in perf,
                   # but that uses different processes for the individual runs, and there is apparently no way to merge
                   # the perf profiles of those different runs.
+                  echo "*** Running PR-branch perf tests for $client vs. $server"
+                  pgrep "$SERVER_TAG" || true
                   # shellcheck disable=SC2086
                   nice -n -20 setarch --addr-no-randomize cset proc --set=cpu2 --exec \
                     perf -- $PERF_OPT -o "$WORKSPACE/$FILENAME.server.perf" $WORKSPACE/$SERVER_CMD &
@@ -350,6 +385,7 @@ jobs:
                   pkill "$SERVER_TAG"
                   cd "$WORKSPACE"
 
+                  echo "*** Preparing results report for $client vs. $server"
                   if [[ "$client" == "neqo" && "$server" == "neqo" && "$cc" == "cubic" && "$pacing" == "on" ||
                         "$client" == "$server" && "$client" != "neqo" && "$server" != "neqo" ]]; then
                     BOLD="**"
