From `mtu`

diff --git a/.github/workflows/check-vm.yml b/.github/workflows/check-vm.yml
--- a/.github/workflows/check-vm.yml
+++ b/.github/workflows/check-vm.yml
@@ -8,6 +8,9 @@ on:
     paths-ignore: ["*.md", "*.png", "*.svg", "LICENSE-*"]
   merge_group:
   workflow_dispatch:
+env:
+  CARGO_TERM_COLOR: always
+  RUST_BACKTRACE: 1
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref_name }}
@@ -25,52 +28,82 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
       - if: matrix.os == 'freebsd'
-        uses: vmactions/freebsd-vm@d7b8fcc7711aa41ad45e8d9b737cf90f035a7e3d
+        uses: vmactions/freebsd-vm@debf37ca7b7fa40e19c542ef7ba30d6054a706a4
         with:
           usesh: true
-          copyback: false
+          envs: "CARGO_TERM_COLOR RUST_BACKTRACE GITHUB_ACTIONS"
           prepare: |
-            mkdir -p /usr/local/etc/pkg/repos
-            sed 's/quarterly/latest/' /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
-            pkg update
-            pkg install -y rust nss pkgconf
+            pkg install -y curl llvm
           run: |
-            cargo check --all-targets --features ci
-            RUST_LOG=trace cargo test --features ci --no-fail-fast
+            sh rustup.sh --default-toolchain stable --component llvm-tools -y
+            . "$HOME/.cargo/env"
+            export RUST_LOG=trace
+            cargo install cargo-llvm-cov --locked
+            cargo check --all-targets
+            cargo clippy
+            cargo llvm-cov test --no-fail-fast --lcov --output-path lcov.info
+            cargo test --no-fail-fast --release
 
       - if: matrix.os == 'openbsd'
-        uses: vmactions/openbsd-vm@ebafa4eac4adf5e7d04e5bbb4aa764b75dd160df
+        uses: vmactions/openbsd-vm@0cfe06e734a0ea3a546fca7ebf200b984b94d58a
         with:
           usesh: true
-          copyback: false
+          envs: "CARGO_TERM_COLOR RUST_BACKTRACE GITHUB_ACTIONS"
           prepare: |
-            pkg_add rust nss pkgconf
+            pkg_add rust llvm-16.0.6p30 # rustup doesn't support OpenBSD at all
           run: |
-            cargo check --all-targets --features ci
-            RUST_LOG=trace cargo test --features ci --no-fail-fast
+            export LIBCLANG_PATH=/usr/local/llvm16/lib
+            export RUST_LOG=trace
+            cargo check --all-targets
+            cargo clippy
+            cargo test --no-fail-fast
+            cargo test --no-fail-fast --release
 
       - if: matrix.os == 'netbsd'
-        uses: vmactions/netbsd-vm@dd0161ecbb6386e562fd098acf367633501487a4
+        uses: vmactions/netbsd-vm@7c9086fdb4cc1aa814cda6e305390c2b966551a9
         with:
           usesh: true
-          copyback: false
+          envs: "CARGO_TERM_COLOR RUST_BACKTRACE GITHUB_ACTIONS"
           prepare: |
-            /usr/sbin/pkg_add rust nss pkgconf
+            /usr/sbin/pkg_add pkgin
+            pkgin -y install curl clang
           run: |
-            cargo check --all-targets --features ci
-            RUST_LOG=trace cargo test --features ci --no-fail-fast
+            sh rustup.sh --default-toolchain stable --component llvm-tools -y
+            . "$HOME/.cargo/env"
+            export LIBCLANG_PATH=/usr/pkg/lib
+            export RUST_LOG=trace
+            cargo install cargo-llvm-cov --locked
+            cargo check --all-targets
+            cargo clippy
+            cargo test --no-fail-fast
+            # FIXME: error[E0463]: can't find crate for `profiler_builtins`,
+            # so don't fail the workflow when that happens.
+            cargo llvm-cov test --no-fail-fast --lcov --output-path lcov.info || true
+            cargo test --no-fail-fast --release
 
       - if: matrix.os == 'solaris'
-        uses: vmactions/solaris-vm@960d7483ffd6ac03397964cf6423a2f41332c9c8
+        uses:  vmactions/solaris-vm@a89b9438868c70db27e41625f0a5de6ff5e90809
         with:
           release: "11.4-gcc"
           usesh: true
-          copyback: false
+          envs: "CARGO_TERM_COLOR RUST_BACKTRACE GITHUB_ACTIONS"
           prepare: |
             pkg install cargo nss pkg-config
           run: |
+            sh rustup.sh --default-toolchain stable --component llvm-tools -y
+            . "$HOME/.cargo/env"
+            export RUST_LOG=trace
             cargo check --all-targets --features ci
             RUST_LOG=trace cargo test --features ci --no-fail-fast
+
+      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
+        with:
+          file: lcov.info
+          fail_ci_if_error: false
+          token: ${{ secrets.CODECOV_TOKEN }}
+          verbose: true
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
