Expand the CI matrix and generate coverage information (#1500)
* Expand the CI matrix and generate coverage information.

TODO: Support Windows.

* Undo modification to neqo-common/src/hrtime.rs

* Remove debug commands

* Minimize diff

* Update .github/workflows/check.yml

Co-authored-by: Martin Thomson <mt@lowentropy.net>

* Fixes

* A lot of fixes

* Run tests and coverage at the same time. Set Windows DLL path.

* Re-enable stable

---------

Co-authored-by: Martin Thomson <mt@lowentropy.net>

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -5,72 +5,67 @@ env:
 
 jobs:
   check:
-    name: Neqo Build and Test
-    runs-on: ubuntu-22.04
-    env:
-      RUSTFLAGS: -C link-arg=-fuse-ld=lld
+    name: Build & test
     strategy:
+      fail-fast: false
       matrix:
-        rust-toolchain: [stable, 1.65.0]
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        # TODO: add beta (and nightly?) but don't fail the test if they fail
+        rust-toolchain: [1.65.0, stable]
+    runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        shell: bash
 
     steps:
-      - name: Install Packages
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@master
+        with:
+          toolchain: ${{ matrix.rust-toolchain }}
+          components: rustfmt, clippy
+
+      - name: Install dependencies (Linux)
+        if: runner.os == 'Linux'
         env:
           DEBIAN_FRONTEND: noninteractive
-          llvm_version: 14
         run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            build-essential \
-            clang \
-            coreutils \
-            curl \
-            git \
-            gyp \
-            libclang-dev \
-            libssl-dev \
-            lld \
-            llvm-"$llvm_version" \
-            llvm-"$llvm_version"-runtime \
-            make \
-            mercurial \
-            ninja-build \
-            pkg-config \
-            ssh \
-            zlib1g-dev \
-            --no-install-recommends
-          [ -d "/usr/lib/llvm-$llvm_version/lib" ]
-          echo "LIBCLANG_DIR=/usr/lib/llvm-$llvm_version/lib" >> "$GITHUB_ENV"
+          sudo apt-get install -y --no-install-recommends gyp mercurial ninja-build
+          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
 
-      # Rust installation cribbed from Dockerfiles at https://github.com/rust-lang/docker-rust
-      - name: Install Rust
+      - name: Install dependencies (MacOS)
+        if: runner.os == 'MacOS'
         run: |
-          export RUSTUP_HOME=~/.rustup
-          export CARGO_HOME=~/.cargo
-          rustup_dir=`mktemp -d /tmp/rustup-XXXXX`
-          mkdir -p "$rustup_dir"
-          rustup_init="$rustup_dir/rustup-init"
-          rustup_url="https://static.rust-lang.org/rustup/archive/$rustup_version/$rustup_host/rustup-init"
-          curl -SsLf "$rustup_url" -o "$rustup_init"
-          echo "${rustup_hash} $rustup_init" | sha256sum -c -
-          chmod +x "$rustup_init"
-          "$rustup_init" -y -q --no-modify-path --profile minimal \
-            --default-toolchain ${{ matrix.rust-toolchain }} \
-            --default-host "$rustup_host" \
-            --component clippy --component rustfmt
-          rm -rf "$rustup_dir"
-          chmod -R a+w "$RUSTUP_HOME" "$CARGO_HOME"
-          "$CARGO_HOME/bin/rustup" default ${{ matrix.rust-toolchain }}
-          echo "RUSTUP_HOME=$RUSTUP_HOME" >> "$GITHUB_ENV"
-          echo "CARGO_HOME=$CARGO_HOME" >> "$GITHUB_ENV"
-          echo "$CARGO_HOME/bin" >> "$GITHUB_PATH"
-        env:
-          rustup_version: 1.26.0
-          rustup_host: x86_64-unknown-linux-gnu
-          rustup_hash: 0b2f6c8f85a3d02fde2efc0ced4657869d73fccfce59defb4e8d29233116e6db
+          brew install ninja mercurial cargo-binstall
+          # python3 -m pip install gyp-next
+          # Above does not work, since pypi only has gyp 0.15.0, which is too old
+          # for the homebrew python3. Install from source instead.
+          python3 -m pip install git+https://github.com/nodejs/gyp-next
+          python3 -m pip install packaging
+          echo "$(python3 -m site --user-base)/bin" >> "$GITHUB_PATH"
+
+      - name: Install dependencies (Windows)
+        if: runner.os == 'Windows'
+        shell: pwsh
+        run: Set-ExecutionPolicy Unrestricted -Scope Process; iex (iwr "https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1").Content
+
+      - name: Use MSYS2 environment and install more dependencies (Windows)
+        if: runner.os == 'Windows'
+        run: |
+          echo "C:\\msys64\\usr\\bin" >> "$GITHUB_PATH"
+          echo "C:\\msys64\\mingw64\\bin" >> "$GITHUB_PATH"
+          /c/msys64/usr/bin/pacman -S --noconfirm nsinstall
+          python3 -m pip install git+https://github.com/nodejs/gyp-next
+          echo "$(python3 -m site --user-base)/bin" >> "$GITHUB_PATH"
+
+      - name: Set up Windows build environment
+        if: runner.os == 'Windows'
+        uses: ilammy/msvc-dev-cmd@v1
+
+      - name: Install Rust tools
+        run: cargo +${{ matrix.rust-toolchain }} binstall --no-confirm cargo-llvm-cov cargo-nextest
 
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       # This step might be removed if the distro included a recent enough
       # version of NSS.  Ubuntu 20.04 only has 3.49, which is far too old.
@@ -82,24 +77,47 @@ jobs:
           git clone --depth=1 https://github.com/nss-dev/nss "$NSS_DIR"
           echo "NSS_DIR=$NSS_DIR" >> "$GITHUB_ENV"
           echo "NSPR_DIR=$NSPR_DIR" >> "$GITHUB_ENV"
+          echo "NSS_JOBS=$NUMBER_OF_PROCESSORS" >> "$GITHUB_ENV"
         env:
           NSS_DIR: ${{ github.workspace }}/nss
           NSPR_DIR: ${{ github.workspace }}/nspr
 
-      - name: Build
-        run: cargo +${{ matrix.rust-toolchain }} build -v --tests
+      - name: Set up environment for NSS build.sh (Windows)
+        if: runner.os == 'Windows'
+        run: |
+          echo "GYP_MSVS_OVERRIDE_PATH=$VSINSTALLDIR" >> "$GITHUB_ENV"
+          echo "GYP_MSVS_VERSION=2022" >> "$GITHUB_ENV"
+          echo "BASH=$SHELL" >> "$GITHUB_ENV"
+          # See https://github.com/ilammy/msvc-dev-cmd#name-conflicts-with-shell-bash
+          rm /usr/bin/link.exe
 
-      - name: Run Tests
-        run: cargo +${{ matrix.rust-toolchain }} test -v
+      - name: Build
+        run: |
+          cargo +${{ matrix.rust-toolchain }} build -v --all-targets
+          echo "LD_LIBRARY_PATH=${{ github.workspace }}/dist/Debug/lib" >> "$GITHUB_ENV"
+          echo "DYLD_LIBRARY_PATH=${{ github.workspace }}/dist/Debug/lib" >> "$GITHUB_ENV"
+          echo "${{ github.workspace }}/dist/Debug/lib" >> "$GITHUB_PATH"
         env:
-           LD_LIBRARY_PATH: ${{ github.workspace }}/dist/Debug/lib
-           RUST_BACKTRACE: 1
-           RUST_LOG: neqo=debug
+          RUST_BACKTRACE: 1
+
+      - name: Run tests and determine coverage
+        run: cargo +${{ matrix.rust-toolchain }} llvm-cov nextest --all-targets --no-fail-fast --lcov --output-path lcov.info
+        env:
+          RUST_BACKTRACE: 1
+          RUST_LOG: neqo=debug
 
       - name: Check formatting
         run: cargo +${{ matrix.rust-toolchain }} fmt --all -- --check
-        if: ${{ success() || failure() }}
+        if: success() || failure()
 
       - name: Clippy
         run: cargo +${{ matrix.rust-toolchain }} clippy -v --tests -- -D warnings
-        if: ${{ success() || failure() }}
+        if: success() || failure()
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
+        with:
+          file: lcov.info
+          fail_ci_if_error: true
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
