Again

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -80,7 +80,7 @@ jobs:
         uses: ilammy/msvc-dev-cmd@v1
 
       - name: Install Rust tools
-        run: cargo +${{ matrix.rust-toolchain }} binstall --no-confirm cargo-llvm-cov
+        run: cargo +${{ matrix.rust-toolchain }} binstall --no-confirm cargo-llvm-cov cargo-nextest
 
       - name: Checkout
         uses: actions/checkout@v4
@@ -117,16 +117,15 @@ jobs:
 
       - name: Run tests and determine coverage
         run: |
-          env | sort
-          cargo +${{ matrix.rust-toolchain }} llvm-cov test --features ci --all-targets --no-fail-fast --lcov --output-path lcov.info
-        env:
-          DYLD_PRINT_LIBRARIES: true
+          cargo +${{ matrix.rust-toolchain }} llvm-cov nextest --features ci --all-targets --no-fail-fast --lcov --output-path lcov.info
+        # env:
+        #   DYLD_PRINT_LIBRARIES: true
 
-      - name: libplds4
-        run: |
-          find "${{ github.workspace }}" -ls | grep libplds4
-          find "$DYLD_LIBRARY_PATH" -ls
-        if: success() || failure()
+      # - name: libplds4
+      #   run: |
+      #     find "${{ github.workspace }}" -ls | grep libplds4
+      #     find "$DYLD_LIBRARY_PATH" -ls
+      #   if: success() || failure()
 
       - name: Check formatting
         run: cargo +${{ matrix.rust-toolchain }} fmt --all -- --check
